/**
 * Return the full HTML document for the AL EventLens webview panel.
 * The returned string includes inline CSS and JS — the panel is a single
 * self-contained document with no external resources, so it works
 * identically on desktop and VS Code Web. The supplied `nonce` is the
 * value used in the CSP meta and on the inline `<script>` tag.
 */
export function renderPanelHtml(nonce: string): string {
  const css = [
    'html, body { margin: 0; padding: 0; height: 100%; box-sizing: border-box; }',
    'body { font-family: var(--vscode-font-family); background: var(--vscode-editor-background); color: var(--vscode-editor-foreground); }',
    '.root { display: flex; height: 100vh; --left-width: 30%; }',
    '.left { flex: 0 0 var(--left-width); min-width: 150px; overflow: hidden; display: flex; flex-direction: column; }',
    '.divider { flex: 0 0 4px; background: var(--vscode-panel-border); cursor: col-resize; user-select: none; }',
    '.divider:hover, .divider.dragging { background: var(--vscode-focusBorder, var(--vscode-panel-border)); }',
    '.right { flex: 1; min-width: 200px; padding: 12px; overflow: auto; }',
    '#search { margin: 8px; padding: 6px 8px; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border); font: inherit; outline: none; }',
    '.list { list-style: none; margin: 0; padding: 0; flex: 1; overflow-y: auto; }',
    '.list li { padding: 4px 10px; cursor: pointer; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }',
    '.list li.empty { cursor: default; }',
    '.list li:hover { background: var(--vscode-list-hoverBackground); }',
    '.list li.selected { background: var(--vscode-list-activeSelectionBackground); color: var(--vscode-list-activeSelectionForeground); }',
    '.detail-header { font-weight: bold; margin-bottom: 4px; }',
    '.detail-meta { color: var(--vscode-descriptionForeground); margin-bottom: 12px; font-size: 0.9em; }',
    '.sub-list { list-style: none; margin: 8px 0 0 0; padding: 0; }',
    '.sub-list li { padding: 3px 4px; cursor: pointer; }',
    '.sub-list li.unresolved { cursor: default; }',
    '.sub-list li:hover { background: var(--vscode-list-hoverBackground); }',
    '.badge { display: inline-block; width: 1em; margin-right: 6px; text-align: center; }',
    '.badge-ok { color: var(--vscode-charts-green); }',
    '.badge-warn { color: var(--vscode-editorWarning-foreground); }',
    '.file-path { color: var(--vscode-descriptionForeground); margin-left: 8px; font-size: 0.9em; }',
    '.empty { color: var(--vscode-descriptionForeground); padding: 4px; }'
  ].join('\n    ');

  const js = [
    'const vscode = acquireVsCodeApi();',
    'let publishers = [];',
    'let subscribers = [];',
    'let selectedKey = null;',
    '',
    "function keyOf(p) { return p.owner.name + '::' + p.eventName; }",
    '',
    'function findSubscribersFor(p) {',
    '  const targetName = p.owner.name.toLowerCase();',
    '  const targetEvent = p.eventName.toLowerCase();',
    '  return subscribers.filter(function (s) {',
    '    return s.target.name.toLowerCase() === targetName && s.targetEvent.toLowerCase() === targetEvent;',
    '  });',
    '}',
    '',
    'function pathOf(loc) {',
    '  if (!loc || !loc.uri) return null;',
    '  return loc.uri.fsPath || loc.uri.path || null;',
    '}',
    '',
    'function lineOf(loc) {',
    '  if (!loc || !loc.range || !loc.range.start) return 0;',
    '  return (loc.range.start.line | 0) + 1;',
    '}',
    '',
    'function renderList() {',
    "  const search = (document.getElementById('search').value || '').toLowerCase();",
    "  const ul = document.getElementById('publishers');",
    '  while (ul.firstChild) ul.removeChild(ul.firstChild);',
    '  let shown = 0;',
    '  publishers.forEach(function (p) {',
    "    const hay = (p.owner.name + ' ' + p.eventName).toLowerCase();",
    "    if (search && hay.indexOf(search) === -1) return;",
    "    const li = document.createElement('li');",
    "    li.textContent = p.owner.kind + '::\"' + p.owner.name + '\" · ' + p.eventName;",
    "    if (keyOf(p) === selectedKey) li.classList.add('selected');",
    "    li.addEventListener('click', function () {",
    '      selectedKey = keyOf(p);',
    "      vscode.postMessage({ type: 'selectionChanged', publisher: p });",
    '      render();',
    '    });',
    '    ul.appendChild(li);',
    '    shown++;',
    '  });',
    '  if (shown === 0) {',
    "    const li = document.createElement('li');",
    "    li.className = 'empty';",
    "    li.textContent = publishers.length === 0 ? 'No publishers indexed yet.' : 'No matches.';",
    '    ul.appendChild(li);',
    '  }',
    '}',
    '',
    'function renderDetail() {',
    "  const detail = document.getElementById('detail');",
    '  while (detail.firstChild) detail.removeChild(detail.firstChild);',
    '  const selected = publishers.find(function (p) { return keyOf(p) === selectedKey; });',
    '  if (!selected) {',
    "    detail.textContent = 'Select a publisher.';",
    '    return;',
    '  }',
    "  const header = document.createElement('div');",
    "  header.className = 'detail-header';",
    "  header.textContent = selected.owner.kind + '::\"' + selected.owner.name + '\" · ' + selected.eventName;",
    '  detail.appendChild(header);',
    '',
    "  const meta = document.createElement('div');",
    "  meta.className = 'detail-meta';",
    "  meta.textContent = selected.owner.appId ? ('appId: ' + selected.owner.appId) : '(workspace)';",
    '  detail.appendChild(meta);',
    '',
    '  const matches = findSubscribersFor(selected);',
    '  if (matches.length === 0) {',
    "    const empty = document.createElement('div');",
    "    empty.className = 'empty';",
    "    empty.textContent = 'No subscribers.';",
    '    detail.appendChild(empty);',
    '    return;',
    '  }',
    "  const subUl = document.createElement('ul');",
    "  subUl.className = 'sub-list';",
    '  matches.forEach(function (s) {',
    "    const li = document.createElement('li');",
    "    const badge = document.createElement('span');",
    "    badge.className = 'badge ' + (s.resolved ? 'badge-ok' : 'badge-warn');",
    "    badge.textContent = s.resolved ? '\\u2713' : '\\u26A0';",
    '    li.appendChild(badge);',
    "    const label = document.createElement('span');",
    "    label.textContent = s.owner.kind + '::\"' + s.owner.name + '\"';",
    '    li.appendChild(label);',
    "    const trail = document.createElement('span');",
    "    trail.className = 'file-path';",
    '    if (s.resolved) {',
    '      const path = pathOf(s.location);',
    "      trail.textContent = (path || '') + ':' + lineOf(s.location);",
    "      li.addEventListener('click', function () {",
    "        vscode.postMessage({ type: 'gotoSubscriber', subscriber: s });",
    '      });',
    '    } else {',
    "      li.classList.add('unresolved');",
    "      trail.textContent = 'target app missing from .alpackages';",
    '    }',
    '    li.appendChild(trail);',
    '    subUl.appendChild(li);',
    '  });',
    '  detail.appendChild(subUl);',
    '}',
    '',
    'function render() { renderList(); renderDetail(); }',
    '',
    'function scrollSelectedIntoView() {',
    "  const ul = document.getElementById('publishers');",
    "  const sel = ul.querySelector('li.selected');",
    "  if (sel && typeof sel.scrollIntoView === 'function') sel.scrollIntoView({ block: 'nearest' });",
    '}',
    '',
    "window.addEventListener('message', function (e) {",
    '  const m = e.data;',
    '  if (!m) return;',
    "  if (m.type === 'index') {",
    '    publishers = m.publishers || [];',
    '    subscribers = m.subscribers || [];',
    '    render();',
    "  } else if (m.type === 'select' && m.publisher) {",
    '    selectedKey = keyOf(m.publisher);',
    '    render();',
    '    scrollSelectedIntoView();',
    '  }',
    '});',
    '',
    "document.getElementById('search').addEventListener('input', render);",
    '',
    "(function initDivider() {",
    "  const root = document.querySelector('.root');",
    "  const divider = document.getElementById('divider');",
    '  let dragging = false;',
    '  function setLeftWidth(px) {',
    '    const rect = root.getBoundingClientRect();',
    '    const min = 150;',
    '    const max = Math.max(min, rect.width - 200);',
    '    const clamped = Math.max(min, Math.min(max, px));',
    "    root.style.setProperty('--left-width', clamped + 'px');",
    '    try { vscode.setState({ leftWidth: clamped }); } catch (_) {}',
    '  }',
    "  divider.addEventListener('pointerdown', function (e) {",
    '    dragging = true;',
    "    divider.classList.add('dragging');",
    '    try { divider.setPointerCapture(e.pointerId); } catch (_) {}',
    '    e.preventDefault();',
    '  });',
    "  divider.addEventListener('pointermove', function (e) {",
    '    if (!dragging) return;',
    '    const rect = root.getBoundingClientRect();',
    '    setLeftWidth(e.clientX - rect.left);',
    '  });',
    '  function endDrag(e) {',
    '    if (!dragging) return;',
    '    dragging = false;',
    "    divider.classList.remove('dragging');",
    '    try { divider.releasePointerCapture(e.pointerId); } catch (_) {}',
    '  }',
    "  divider.addEventListener('pointerup', endDrag);",
    "  divider.addEventListener('pointercancel', endDrag);",
    '  const saved = vscode.getState();',
    "  if (saved && typeof saved.leftWidth === 'number') {",
    '    setLeftWidth(saved.leftWidth);',
    '  }',
    '})();',
    '',
    'render();'
  ].join('\n      ');

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8">',
    `  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}';">`,
    '  <title>AL EventLens</title>',
    '  <style>',
    `    ${css}`,
    '  </style>',
    '</head>',
    '<body>',
    '  <div class="root">',
    '    <div class="left">',
    '      <input id="search" placeholder="Search publishers...">',
    '      <ul id="publishers" class="list"></ul>',
    '    </div>',
    '    <div id="divider" class="divider" role="separator" aria-orientation="vertical"></div>',
    '    <div class="right">',
    '      <div id="detail">Select a publisher.</div>',
    '    </div>',
    '  </div>',
    `  <script nonce="${nonce}">`,
    `      ${js}`,
    '  </script>',
    '</body>',
    '</html>'
  ].join('\n');
}
