/**
 * Return the full HTML document for the AL EventLens webview panel.
 * The returned string includes inline CSS and JS — the panel is a single
 * self-contained document with no external resources, so it works
 * identically on desktop and VS Code Web. The supplied `nonce` is the
 * value used in the CSP meta and on the inline `<script>` tag.
 */
export function renderPanelHtml(nonce: string): string {
  const css = [
    'html, body { margin: 0; padding: 0; height: 100%; box-sizing: border-box; }',
    'body { font-family: var(--vscode-font-family); background: var(--vscode-editor-background); color: var(--vscode-editor-foreground); }',
    '.root { display: flex; height: 100vh; --left-width: 30%; }',
    '.left { flex: 0 0 var(--left-width); min-width: 150px; overflow: hidden; display: flex; flex-direction: column; }',
    '.divider { flex: 0 0 4px; background: var(--vscode-panel-border); cursor: col-resize; user-select: none; }',
    '.divider:hover, .divider.dragging { background: var(--vscode-focusBorder, var(--vscode-panel-border)); }',
    '.right { flex: 1; min-width: 200px; padding: 12px; overflow: auto; }',
    '.filters { display: flex; gap: 4px; margin: 8px 8px 0 8px; }',
    '.filters select { flex: 1; min-width: 0; padding: 4px 6px; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border); font: inherit; outline: none; }',
    '#search { margin: 4px 8px 8px 8px; padding: 6px 8px; background: var(--vscode-input-background); color: var(--vscode-input-foreground); border: 1px solid var(--vscode-input-border); font: inherit; outline: none; }',
    '.list { list-style: none; margin: 0; padding: 0; flex: 1; overflow-y: auto; }',
    '.list li { padding: 4px 10px; cursor: pointer; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }',
    '.list li.empty { cursor: default; }',
    '.list li:hover { background: var(--vscode-list-hoverBackground); }',
    '.list li.selected { background: var(--vscode-list-activeSelectionBackground); color: var(--vscode-list-activeSelectionForeground); }',
    '.detail-header { font-weight: bold; margin-bottom: 4px; }',
    '.detail-signature { font-family: var(--vscode-editor-font-family, monospace); color: var(--vscode-descriptionForeground); margin-bottom: 4px; font-size: 0.9em; word-break: break-word; }',
    '.detail-signature .param-var { color: var(--vscode-symbolIcon-keywordForeground, var(--vscode-descriptionForeground)); font-style: italic; }',
    '.detail-meta { color: var(--vscode-descriptionForeground); margin-bottom: 12px; font-size: 0.9em; }',
    '.sub-list { list-style: none; margin: 8px 0 0 0; padding: 0; }',
    '.sub-list li { padding: 3px 4px; cursor: pointer; }',
    '.sub-list li:hover { background: var(--vscode-list-hoverBackground); }',
    '.badge { display: inline-block; width: 1em; margin-right: 6px; text-align: center; }',
    '.badge-ok { color: var(--vscode-charts-green); }',
    '.badge-warn { color: var(--vscode-editorWarning-foreground); }',
    '.file-path { color: var(--vscode-descriptionForeground); margin-left: 8px; font-size: 0.9em; }',
    '.empty { color: var(--vscode-descriptionForeground); padding: 4px; }'
  ].join('\n    ');

  const js = [
    'const vscode = acquireVsCodeApi();',
    'let publishers = [];',
    'let subscribers = [];',
    'let appMetaMap = new Map();',
    'let subscribersByKey = new Map();',
    'let selectedKey = null;',
    "let selectedLi = null;",
    '',
    '// formatKind mirror — must match src/al/format.ts. Webview JS cannot',
    '// import TS modules, so the table is duplicated.',
    'const KIND_LABELS = {',
    "  codeunit: 'Codeunit', table: 'Table', tableextension: 'TableExtension',",
    "  page: 'Page', pageextension: 'PageExtension', report: 'Report',",
    "  reportextension: 'ReportExtension', query: 'Query', xmlport: 'XmlPort',",
    "  enum: 'Enum', enumextension: 'EnumExtension', permissionset: 'PermissionSet',",
    "  interface: 'Interface'",
    '};',
    "function formatKind(k) { return KIND_LABELS[k] || k; }",
    '',
    "function keyOf(p) { return p.owner.kind + ' ' + p.owner.name.toLowerCase() + ' ' + p.eventName.toLowerCase(); }",
    '',
    "function appLabelFor(appId) {",
    "  if (!appId) return '(workspace)';",
    '  const meta = appMetaMap.get(appId);',
    '  return (meta && meta.name) ? meta.name : appId;',
    '}',
    '',
    '// Tokenize a search string into whitespace-separated parts. Three forms',
    '// are recognized so prefixes can carry values with spaces:',
    '//   (a) `<word>::"..."` — AL-style identity selector, e.g.',
    "//       `codeunit::\"Sales Header\"`. Returned verbatim (quotes intact)",
    '//       so parseSearch can recognize the structure.',
    '//   (b) `"..."` — bare quoted value, e.g. `object:"Sales Header"`.',
    '//       Tokenizer strips the surrounding quotes.',
    '//   (c) `\\S+` — any non-whitespace run.',
    'function tokenizeSearch(text) {',
    '  const tokens = [];',
    "  const re = /(\\w+::\"[^\"]*\")|\"([^\"]*)\"|(\\S+)/g;",
    '  let m;',
    '  while ((m = re.exec(text || \'\')) !== null) {',
    '    if (m[1] !== undefined) tokens.push(m[1]);',
    '    else if (m[2] !== undefined) tokens.push(m[2]);',
    '    else tokens.push(m[3]);',
    '  }',
    '  return tokens;',
    '}',
    '',
    "function parseSearch(text) {",
    "  const tokens = tokenizeSearch(text);",
    "  let app = '', kind = '', object = '';",
    '  let objectIdentity = null;',
    '  const free = [];',
    '  for (let i = 0; i < tokens.length; i++) {',
    '    const t = tokens[i];',
    '    // AL-style identity selector: `Codeunit::"Sales-Post"` matches the',
    '    // exact (kind, name) pair, case-insensitive. Inner name may be bare',
    '    // (no spaces) or quoted. Also sets `kind` so the Kind dropdown stays',
    "    // in sync with what the filter is doing.",
    "    const idMatch = /^(\\w+)::(?:\"([^\"]*)\"|(\\S+))$/.exec(t);",
    '    if (idMatch) {',
    '      objectIdentity = {',
    '        kind: idMatch[1].toLowerCase(),',
    '        name: (idMatch[2] !== undefined ? idMatch[2] : idMatch[3]).toLowerCase()',
    '      };',
    '      if (!kind) kind = objectIdentity.kind;',
    '      continue;',
    '    }',
    "    if (t.length > 4 && t.slice(0, 4).toLowerCase() === 'app:') app = t.slice(4).toLowerCase();",
    "    else if (t.length > 5 && t.slice(0, 5).toLowerCase() === 'kind:') kind = t.slice(5).toLowerCase();",
    "    else if (t.length > 7 && t.slice(0, 7).toLowerCase() === 'object:') object = t.slice(7).toLowerCase();",
    '    else free.push(t.toLowerCase());',
    '  }',
    "  return { app: app, kind: kind, object: object, objectIdentity: objectIdentity, free: free.join(' ') };",
    '}',
    '',
    '// Re-quote a token value when it contains whitespace or quotes so the',
    "// serialized search string round-trips through tokenizeSearch. Quotes in",
    "// the value are stripped (the tokenizer can't represent escaped quotes).",
    'function quoteIfNeeded(v) {',
    "  if (/\\s|\"/.test(v)) return '\"' + v.replace(/\"/g, '') + '\"';",
    '  return v;',
    '}',
    '',
    'function buildSearchText(parsed) {',
    '  const parts = [];',
    "  if (parsed.app) parts.push('app:' + quoteIfNeeded(parsed.app));",
    '  if (parsed.objectIdentity) {',
    '    // Emit as `<kind>::<name>` / `<kind>::"name with spaces"`. The kind',
    '    // is implied by the identity selector, so the bare `kind:` token is',
    "    // suppressed unless it disagrees (a contradictory edge case).",
    '    const id = parsed.objectIdentity;',
    "    const namePart = /\\s|\"/.test(id.name) ? '\"' + id.name.replace(/\"/g, '') + '\"' : id.name;",
    "    parts.push(id.kind + '::' + namePart);",
    '    if (parsed.kind && parsed.kind !== id.kind) {',
    "      parts.push('kind:' + quoteIfNeeded(parsed.kind));",
    '    }',
    '  } else {',
    "    if (parsed.kind) parts.push('kind:' + quoteIfNeeded(parsed.kind));",
    '  }',
    "  if (parsed.object) parts.push('object:' + quoteIfNeeded(parsed.object));",
    '  if (parsed.free) parts.push(parsed.free);',
    "  return parts.join(' ');",
    '}',
    '',
    "function passesFilter(p, parsed) {",
    '  if (parsed.objectIdentity) {',
    "    // Exact (kind, name) match — case-insensitive. Identity check beats",
    "    // any same-named object of a different kind that the looser `object:`",
    "    // substring would also surface.",
    '    if (p.owner.kind.toLowerCase() !== parsed.objectIdentity.kind) return false;',
    '    if (p.owner.name.toLowerCase() !== parsed.objectIdentity.name) return false;',
    '  }',
    "  if (parsed.kind && p.owner.kind.toLowerCase() !== parsed.kind) return false;",
    '  if (parsed.app) {',
    '    const label = appLabelFor(p.owner.appId).toLowerCase();',
    "    const guid = (p.owner.appId || '').toLowerCase();",
    '    if (label.indexOf(parsed.app) === -1 && guid.indexOf(parsed.app) === -1) return false;',
    '  }',
    '  if (parsed.object) {',
    '    if (p.owner.name.toLowerCase().indexOf(parsed.object) === -1) return false;',
    '  }',
    '  if (parsed.free) {',
    "    const hay = (p.owner.name + ' ' + p.eventName).toLowerCase();",
    '    if (hay.indexOf(parsed.free) === -1) return false;',
    '  }',
    '  return true;',
    '}',
    '',
    'function populateFilters() {',
    "  const appSelect = document.getElementById('filterApp');",
    "  const kindSelect = document.getElementById('filterKind');",
    '  // app options: unique appIds in publishers (workspace first)',
    '  const seenApps = new Set();',
    '  let hasWorkspace = false;',
    '  const appOpts = [];',
    '  publishers.forEach(function (p) {',
    '    if (!p.owner.appId) { hasWorkspace = true; return; }',
    '    if (seenApps.has(p.owner.appId)) return;',
    '    seenApps.add(p.owner.appId);',
    '    const meta = appMetaMap.get(p.owner.appId);',
    '    const label = (meta && meta.name) ? meta.name : p.owner.appId;',
    "    const vendor = (meta && meta.appPublisher) ? ' (' + meta.appPublisher + ')' : '';",
    '    appOpts.push({ value: label.toLowerCase(), display: label + vendor });',
    '  });',
    '  appOpts.sort(function (a, b) { return a.display.localeCompare(b.display); });',
    "  let html = '<option value=\"\">All apps</option>';",
    '  if (hasWorkspace) {',
    "    html += '<option value=\"(workspace)\">(workspace)</option>';",
    '  }',
    '  appOpts.forEach(function (o) {',
    "    html += '<option value=\"' + escapeAttr(o.value) + '\">' + escapeHtml(o.display) + '</option>';",
    '  });',
    '  appSelect.innerHTML = html;',
    '',
    '  const seenKinds = new Set();',
    '  publishers.forEach(function (p) { seenKinds.add(p.owner.kind); });',
    '  const kindOpts = Array.from(seenKinds).map(function (k) {',
    '    return { value: k, display: formatKind(k) };',
    '  });',
    '  kindOpts.sort(function (a, b) { return a.display.localeCompare(b.display); });',
    "  let kindHtml = '<option value=\"\">All kinds</option>';",
    '  kindOpts.forEach(function (o) {',
    "    kindHtml += '<option value=\"' + escapeAttr(o.value) + '\">' + escapeHtml(o.display) + '</option>';",
    '  });',
    '  kindSelect.innerHTML = kindHtml;',
    '}',
    '',
    "function escapeHtml(s) {",
    "  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');",
    '}',
    "function escapeAttr(s) {",
    "  return escapeHtml(s).replace(/\"/g, '&quot;');",
    '}',
    '',
    '// Render the parameter list as an AL-style signature line, e.g.',
    '// `(var Rec: Record "Sales Header"; RunTrigger: Boolean)`. An empty list',
    '// renders as `()`. Each token is HTML-escaped; the `var` keyword is the',
    '// only structural markup so it can be themed independently.',
    'function renderSignature(params) {',
    "  if (!params.length) return '()';",
    '  const parts = params.map(function (p) {',
    "    const varTag = p.isVar ? '<span class=\"param-var\">var</span> ' : '';",
    "    return varTag + escapeHtml(p.name) + ': ' + escapeHtml(p.typeText);",
    '  });',
    "  return '(' + parts.join('; ') + ')';",
    '}',
    '',
    'function syncDropdownsFromSearch(parsed) {',
    "  const appSelect = document.getElementById('filterApp');",
    "  const kindSelect = document.getElementById('filterKind');",
    "  appSelect.value = parsed.app || '';",
    '  // If the typed value doesn\\\'t match any option, the select falls back to "" (All apps).',
    "  kindSelect.value = parsed.kind || '';",
    '}',
    '',
    'function rebuildSubscribersIndex() {',
    '  subscribersByKey = new Map();',
    '  subscribers.forEach(function (s) {',
    "    const k = s.target.kind + ' ' + s.target.name.toLowerCase() + ' ' + s.targetEvent.toLowerCase();",
    '    let bucket = subscribersByKey.get(k);',
    '    if (!bucket) { bucket = []; subscribersByKey.set(k, bucket); }',
    '    bucket.push(s);',
    '  });',
    '}',
    '',
    'function findSubscribersFor(p) {',
    '  return subscribersByKey.get(keyOf(p)) || [];',
    '}',
    '',
    'function pathOf(loc) {',
    '  if (!loc || !loc.uri) return null;',
    '  return loc.uri.fsPath || loc.uri.path || null;',
    '}',
    '',
    'function lineOf(loc) {',
    '  if (!loc || !loc.range || !loc.range.start) return 0;',
    '  return (loc.range.start.line | 0) + 1;',
    '}',
    '',
    'function renderList() {',
    "  const searchEl = document.getElementById('search');",
    "  const parsed = parseSearch(searchEl.value);",
    '  syncDropdownsFromSearch(parsed);',
    "  const ul = document.getElementById('publishers');",
    '  while (ul.firstChild) ul.removeChild(ul.firstChild);',
    '  selectedLi = null;',
    '  let shown = 0;',
    '  publishers.forEach(function (p) {',
    '    if (!passesFilter(p, parsed)) return;',
    "    const li = document.createElement('li');",
    '    const count = findSubscribersFor(p).length;',
    "    li.textContent = p.owner.kind + '::\"' + p.owner.name + '\" · ' + p.eventName + ' · (' + count + ')';",
    '    const kindLabel = p.kind.charAt(0).toUpperCase() + p.kind.slice(1);',
    "    const appLabel = p.owner.appId || '(workspace)';",
    "    li.title = kindLabel + ' event · ' + count + ' subscriber' + (count === 1 ? '' : 's') + '\\n' + appLabel;",
    '    const k = keyOf(p);',
    '    li.__pubKey = k;',
    '    if (k === selectedKey) {',
    "      li.classList.add('selected');",
    '      selectedLi = li;',
    '    }',
    "    li.addEventListener('click', function () {",
    '      setSelected(k, li);',
    "      vscode.postMessage({ type: 'selectionChanged', publisher: p });",
    '    });',
    '    ul.appendChild(li);',
    '    shown++;',
    '  });',
    '  if (shown === 0) {',
    "    const li = document.createElement('li');",
    "    li.className = 'empty';",
    "    li.textContent = publishers.length === 0 ? 'No publishers indexed yet.' : 'No matches.';",
    '    ul.appendChild(li);',
    '  }',
    '}',
    '',
    "function findLiByKey(key) {",
    "  const ul = document.getElementById('publishers');",
    '  if (!ul) return null;',
    '  for (let i = 0; i < ul.children.length; i++) {',
    '    const li = ul.children[i];',
    "    if (li.__pubKey === key) return li;",
    '  }',
    '  return null;',
    '}',
    '',
    'function setSelected(newKey, newLi) {',
    "  if (selectedLi) { selectedLi.classList.remove('selected'); }",
    '  selectedKey = newKey;',
    '  selectedLi = newLi;',
    "  if (selectedLi) { selectedLi.classList.add('selected'); }",
    '  renderDetail();',
    '}',
    '',
    'function renderDetail() {',
    "  const detail = document.getElementById('detail');",
    '  while (detail.firstChild) detail.removeChild(detail.firstChild);',
    '  const selected = publishers.find(function (p) { return keyOf(p) === selectedKey; });',
    '  if (!selected) {',
    "    detail.textContent = 'Select a publisher.';",
    '    return;',
    '  }',
    "  const header = document.createElement('div');",
    "  header.className = 'detail-header';",
    "  header.textContent = selected.owner.kind + '::\"' + selected.owner.name + '\" · ' + selected.eventName;",
    '  detail.appendChild(header);',
    '',
    '  if (Array.isArray(selected.parameters)) {',
    "    const sig = document.createElement('div');",
    "    sig.className = 'detail-signature';",
    '    sig.innerHTML = renderSignature(selected.parameters);',
    '    detail.appendChild(sig);',
    '  }',
    '',
    "  const meta = document.createElement('div');",
    "  meta.className = 'detail-meta';",
    "  meta.textContent = selected.owner.appId ? ('appId: ' + selected.owner.appId) : '(workspace)';",
    '  detail.appendChild(meta);',
    '',
    '  const matches = findSubscribersFor(selected);',
    '  if (matches.length === 0) {',
    "    const empty = document.createElement('div');",
    "    empty.className = 'empty';",
    "    empty.textContent = 'No subscribers.';",
    '    detail.appendChild(empty);',
    '    return;',
    '  }',
    "  const subUl = document.createElement('ul');",
    "  subUl.className = 'sub-list';",
    '  matches.forEach(function (s) {',
    "    const li = document.createElement('li');",
    "    const badge = document.createElement('span');",
    "    badge.className = 'badge ' + (s.resolved ? 'badge-ok' : 'badge-warn');",
    "    badge.textContent = s.resolved ? '\\u2713' : '\\u26A0';",
    '    li.appendChild(badge);',
    "    const label = document.createElement('span');",
    "    label.textContent = s.owner.kind + '::\"' + s.owner.name + '\"';",
    '    li.appendChild(label);',
    "    const trail = document.createElement('span');",
    "    trail.className = 'file-path';",
    '    // The subscriber\\\'s OWN source location is always valid for parsed',
    '    // subscribers regardless of whether the target publisher resolved —',
    '    // so the click handler attaches in both cases. The badge plus the',
    '    // trail text convey the resolved/unresolved status visually.',
    '    const path = pathOf(s.location);',
    '    const lineN = lineOf(s.location);',
    '    if (s.resolved) {',
    "      trail.textContent = (path || '') + ':' + lineN;",
    "      li.title = s.owner.kind + '::\"' + s.owner.name + '\"' + (path ? '\\n' + path + ':' + lineN : '') + '\\nClick to jump to source';",
    '    } else {',
    "      li.classList.add('unresolved');",
    "      trail.textContent = 'target app missing from .alpackages';",
    "      li.title = s.owner.kind + '::\"' + s.owner.name + '\"' + (path ? '\\n' + path + ':' + lineN : '') + '\\nUnresolved — target app missing from .alpackages\\nClick to jump to subscriber source';",
    '    }',
    "    li.addEventListener('click', function () {",
    "      vscode.postMessage({ type: 'gotoSubscriber', subscriber: s });",
    '    });',
    '    li.appendChild(trail);',
    '    subUl.appendChild(li);',
    '  });',
    '  detail.appendChild(subUl);',
    '}',
    '',
    'function render() { renderList(); renderDetail(); }',
    '',
    'function scrollSelectedIntoView() {',
    "  const ul = document.getElementById('publishers');",
    "  const sel = ul.querySelector('li.selected');",
    "  if (sel && typeof sel.scrollIntoView === 'function') sel.scrollIntoView({ block: 'nearest' });",
    '}',
    '',
    "window.addEventListener('message', function (e) {",
    '  const m = e.data;',
    '  if (!m) return;',
    "  if (m.type === 'index') {",
    '    publishers = m.publishers || [];',
    '    subscribers = m.subscribers || [];',
    '    appMetaMap = new Map(m.appMeta || []);',
    '    rebuildSubscribersIndex();',
    '    populateFilters();',
    '    render();',
    "  } else if (m.type === 'select' && m.publisher) {",
    '    const newKey = keyOf(m.publisher);',
    '    const newLi = findLiByKey(newKey);',
    '    setSelected(newKey, newLi);',
    '    scrollSelectedIntoView();',
    "  } else if (m.type === 'reveal' && typeof m.search === 'string') {",
    "    // Reveal: external trigger (tree click, CodeLens) sets the search box,",
    '    // re-renders the filtered list, and optionally selects + scrolls a',
    '    // specific publisher inside the now-filtered view.',
    "    const searchEl = document.getElementById('search');",
    '    searchEl.value = m.search;',
    "    if (typeof m.selectKey === 'string') {",
    '      selectedKey = m.selectKey;',
    '    }',
    '    render();',
    "    if (typeof m.selectKey === 'string') {",
    '      scrollSelectedIntoView();',
    '    }',
    '  }',
    '});',
    '',
    "document.getElementById('search').addEventListener('input', render);",
    '',
    "(function initFilterDropdowns() {",
    "  const searchEl = document.getElementById('search');",
    '  function applyToken(tokenKey, value) {',
    '    const parsed = parseSearch(searchEl.value);',
    "    parsed[tokenKey] = value || '';",
    "    // Changing the kind dropdown invalidates an identity selector",
    "    // (its kind is bound to the old value). Drop it so the rebuilt",
    "    // search reflects only the new dropdown choice.",
    "    if (tokenKey === 'kind') parsed.objectIdentity = null;",
    '    searchEl.value = buildSearchText(parsed);',
    '    render();',
    '  }',
    "  document.getElementById('filterApp').addEventListener('change', function (e) {",
    "    applyToken('app', (e.target.value || '').toLowerCase());",
    '  });',
    "  document.getElementById('filterKind').addEventListener('change', function (e) {",
    "    applyToken('kind', e.target.value || '');",
    '  });',
    '})();',
    '',
    "(function initDivider() {",
    "  const root = document.querySelector('.root');",
    "  const divider = document.getElementById('divider');",
    '  let dragging = false;',
    '  function setLeftWidth(px) {',
    '    const rect = root.getBoundingClientRect();',
    '    const min = 150;',
    '    const max = Math.max(min, rect.width - 200);',
    '    const clamped = Math.max(min, Math.min(max, px));',
    "    root.style.setProperty('--left-width', clamped + 'px');",
    '    try {',
    '      const prev = vscode.getState();',
    "      vscode.setState(Object.assign({}, prev || {}, { leftWidth: clamped }));",
    '    } catch (_) {}',
    '  }',
    "  divider.addEventListener('pointerdown', function (e) {",
    '    dragging = true;',
    "    divider.classList.add('dragging');",
    '    try { divider.setPointerCapture(e.pointerId); } catch (_) {}',
    '    e.preventDefault();',
    '  });',
    "  divider.addEventListener('pointermove', function (e) {",
    '    if (!dragging) return;',
    '    const rect = root.getBoundingClientRect();',
    '    setLeftWidth(e.clientX - rect.left);',
    '  });',
    '  function endDrag(e) {',
    '    if (!dragging) return;',
    '    dragging = false;',
    "    divider.classList.remove('dragging');",
    '    try { divider.releasePointerCapture(e.pointerId); } catch (_) {}',
    '  }',
    "  divider.addEventListener('pointerup', endDrag);",
    "  divider.addEventListener('pointercancel', endDrag);",
    "  divider.addEventListener('dblclick', function () {",
    "    root.style.removeProperty('--left-width');",
    '    try {',
    '      const prev = vscode.getState();',
    '      if (prev && typeof prev === \'object\') {',
    '        const next = Object.assign({}, prev);',
    '        delete next.leftWidth;',
    '        vscode.setState(next);',
    '      }',
    '    } catch (_) {}',
    '  });',
    '  const saved = vscode.getState();',
    "  if (saved && typeof saved.leftWidth === 'number') {",
    '    setLeftWidth(saved.leftWidth);',
    '  }',
    '})();',
    '',
    'render();'
  ].join('\n      ');

  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '  <meta charset="utf-8">',
    `  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}';">`,
    '  <title>AL EventLens</title>',
    '  <style>',
    `    ${css}`,
    '  </style>',
    '</head>',
    '<body>',
    '  <div class="root">',
    '    <div class="left">',
    '      <div class="filters">',
    '        <select id="filterApp" title="Filter by source app"><option value="">All apps</option></select>',
    '        <select id="filterKind" title="Filter by AL object kind"><option value="">All kinds</option></select>',
    '      </div>',
    '      <input id="search" placeholder="Search publishers... (try app:Foo kind:codeunit)">',
    '      <ul id="publishers" class="list"></ul>',
    '    </div>',
    '    <div id="divider" class="divider" role="separator" aria-orientation="vertical"></div>',
    '    <div class="right">',
    '      <div id="detail">Select a publisher.</div>',
    '    </div>',
    '  </div>',
    `  <script nonce="${nonce}">`,
    `      ${js}`,
    '  </script>',
    '</body>',
    '</html>'
  ].join('\n');
}
